safety:
  ai_stop_classes:
    - person
    - dog
    - cat
  obstacle_distance_threshold: 500.0
  ai_confidence_threshold: 0.60

localization:
  gps_origin:
    x: 0.0
    y: 0.0

geofence:
  min_x: 0.0
  max_x: 10.0
  min_y: 0.0
  max_y: 10.0